<a href="https://colab.research.google.com/github/Jitin-uday/Bharat-intern/blob/main/hh_Copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy   :   NUMERICAL PYTHON : NUMPY IS AN EXTREMELY POPULAR PYTHON MODULE,HEAVILY USED IN SCIENTIFIC COMPUTING

NUMPY's MOST USEFUL FEATURE IS N DIMENSIONAL ARRAY OBJECT(NDARRAY)

# 1.  Different ways to create a NumPy Array & Properties of Array

In [ ]:
import numpy as np
a0=np.array([1,2,3])
a0

array([1, 2, 3])

In [ ]:
# One dimensional array
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
b = np.array([9.0,8.3,7.12])
#print(b)
b

array([9.  , 8.3 , 7.12])

In [ ]:
print(a.dtype)
print(b.dtype)
print(type(a))
print(type(b))
print(a.ndim)
print(b.ndim)
print(a.shape)

int32
float64
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1
1
(4,)


In [ ]:
c=np.array(['a','b','c','d'])
print(type(c))

<class 'numpy.ndarray'>


In [ ]:
d=np.array(['a','bbb','12','1@'])
d

array(['a', 'bbb', '12', '1@'], dtype='<U3')

In [ ]:
e=np.array(['a','bbb','12','1@',1,1.4])
print(type(e))
e

<class 'numpy.ndarray'>


array(['a', 'bbb', '12', '1@', '1', '1.4'], dtype='<U32')

In [ ]:
e=np.array(['a','bbb','12','1@',1,1.4])
e

array(['a', 'bbb', '12', '1@', '1', '1.4'], dtype='<U32')

In [ ]:
f=np.array(['a','bbb','12','1@',1,1.4,{'abcd':"rameash"}])
f
#f.itemsize
#f.dtype

array(['a', 'bbb', '12', '1@', 1, 1.4, {'abcd': 'rameash'}], dtype=object)

ACCESSING THE ELEMENTS OF 1-D ARRAY: WE CAN ACCESS THE ELEMENTS OF 1-D NumPy ARRAY USING INDICES...INDEX STARTS FROM 0 &ENDS AT (NUMBER OF EELEMENTS IN ARRAY - 1)

In [ ]:
a[0]

1

In [ ]:
print(a)
print(a[4])


[1 2 3 4]


IndexError: index 4 is out of bounds for axis 0 with size 4

In [ ]:
#a[4]

In [ ]:
#dir(f)

In [ ]:
a.itemsize

4

In [ ]:
print(b)
b.itemsize

[9.   8.3  7.12]


8

In [ ]:
print(c)
c.itemsize

['a' 'b' 'c' 'd']


4

In [ ]:
print(d)
print(d.itemsize)
a111=np.array(['a' 'bbbb' '12' '1@'])
print(a111.itemsize)

['a' 'bbb' '12' '1@']
12
36


In [ ]:
print(e)
e.itemsize

['a' 'bbb' '12' '1@' '1' '1.4']


128

In [ ]:
d[3].itemsize

8

In [ ]:
e[3].itemsize

8

In [ ]:
print(f)
print(type(f[6]))

['a' 'bbb' '12' '1@' 1 1.4 {'abcd': 'rameash'}]
<class 'dict'>


In [ ]:
print(type(e[3]))

<class 'numpy.str_'>


In [ ]:
len(f[2])

2

2-D ARRAY

In [ ]:
a1=np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [ ]:
a1.ndim

2

In [ ]:
a.ndim

1

In [ ]:
a1.shape

(3, 4)

In [ ]:
a1[0,0]

1

In [ ]:
a1[1,3]

8

In [ ]:
print(a1)
print(a1.shape)
row,col=a1.shape
col

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]
(3, 4)


4

In [ ]:
row

3

In [ ]:
a5=np.zeros((row,col))
for i in range(row):
    for j in range(col):
        a5[i,j]=a1[i,j]+a1[i,j]
print(a5)

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [20. 22. 24. 26.]]


In [ ]:
a1.nbytes

48

ACCESSING ELEMENTS USING SLICING

In [ ]:
a2=np.array([1,2,3,4,5,6,7,8])
print(a2[:])
print(a2[2:5])
print(a2[-1:])
print(a2[:-1])
print(a2[0:-1])

[1 2 3 4 5 6 7 8]
[3 4 5]
[8]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [ ]:
print(a2[-8:])

[1 2 3 4 5 6 7 8]


In [ ]:
print(a2[-8:0])

[]


In [ ]:
print(a2[-8:-3])

[1 2 3 4 5]


In [ ]:
a3=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
a3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a3[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a3[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a3[:1]

array([[1, 2, 3, 4, 5]])

In [ ]:
print(a3)
a3[:1,:]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[1, 2, 3, 4, 5]])

In [ ]:
print(a3)
a3[:,2:3]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 3],
       [ 8],
       [13],
       [18]])

In [ ]:
print(a3)
a3[1:3,1:4]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 7,  8,  9],
       [12, 13, 14]])

In [ ]:
a4=np.array([1,2,3,4], dtype='int16')

In [ ]:
a4.itemsize

2

In [ ]:
a5=np.array([1,2,3,4], dtype='float64')
a5
a5.itemsize

8

In [ ]:
print(a5)
print(a5.size)
print(a5.itemsize)
size=a5.size*a5.itemsize
size

[1. 2. 3. 4.]
4
8


32

In [ ]:
a5.nbytes

32

In [ ]:
a51=np.array([[1,2],[3,4],[5,6]],dtype=complex)
print(a51.itemsize)# CREATES AN ARRAY WITH COMPLEX NUMBERS
size=a51.size*a51.itemsize
print(size)
print(a51.nbytes)

16
96
96


In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
a[1, 5]

13

In [ ]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
a[:,1:-1]

array([[ 2,  3,  4,  5,  6],
       [ 9, 10, 11, 12, 13]])

In [ ]:
a[:,1:-1:2]

array([[ 2,  4,  6],
       [ 9, 11, 13]])

In [ ]:
a3[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a3[1,::2]

array([ 6,  8, 10])

In [ ]:
a3[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

# STRIDES

The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis.

In [ ]:
import numpy as np
x = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]], dtype=np.int32)
x.strides

(20, 4)

In [ ]:
y = np.reshape(np.arange(2*3*4), (2,3,4))
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
y.strides

(48, 16, 4)

In [ ]:
y[1,1,1]

17

# LIST VS NumPy ARRAY

SEVERAL BENEFITS: MAJOR BENEFITS OF NUMPY ARRAY OVER A PYTHON LIST

-- LESS MEMORY

--FAST

--CONVENIENT

In [ ]:
import numpy as np
import time
import sys
# CREATING A LIST OF 1000 ELEMENTS
l=range(1000)
#PRINTING THE SIZE OF THE LIST
print(sys.getsizeof(1)*len(l))
# CREATING A NUMPY ARRAY OF 1000 ELEMENTS
array=np.arange(1000)
#PRINTING THE SIZE OF THE LIST
print(array.size*array.itemsize)

28000
4000


![Screenshot%20%28375%29.png](attachment:Screenshot%20%28375%29.png)

In [ ]:
import numpy as np
import time
import sys

SIZE=100000

l1=range(SIZE)
l2=range(SIZE)

a1=np.arange(SIZE)
a2=np.arange(SIZE)

start=time.time()
result=[(x+y) for x,y in zip(l1,l2)] # LIST COMPREHENSION
#print(result)
print("The time taken by python list took:",(time.time()-start)*1000)

start=time.time()
result=a1+a2
end=time.time()
print("The time taken by python numpy array took:",(end-start)*1000)


The time taken by python list took: 18.986940383911133
The time taken by python numpy array took: 2.9993057250976562


INITIALIZING ARRAYS USING BASIC IN-BUILT FUNCTIONS

In [ ]:
a8=np.arange(1,5)
a8

array([1, 2, 3, 4])

In [ ]:
a9=np.arange(1,22,5)
a9

array([ 1,  6, 11, 16, 21])

In [ ]:
a9=np.arange(1,20,3)
a9

array([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
a9=np.arange(0,20,2)
a9

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [ ]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
np.linspace(1,2.5,10)

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        , 2.16666667, 2.33333333, 2.5       ])

In [ ]:
a11=np.array([[1,2],[3,4],[5,6]])
np.shape(a11)

(3, 2)

In [ ]:
a12=a11.reshape(2,3)
a12

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b=np.arange(12)

c=b.reshape(3,4)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a12=a11.reshape(6,1)
a12

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a14=a11.reshape(1,6)
a14

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a11

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print(a12)
a13=np.ravel(a12)
print(a12)
a13

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


array([1, 2, 3, 4, 5, 6])

In [ ]:
a12

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a5=np.zeros((1,4))
a5

array([[0., 0., 0., 0.]])

In [ ]:
a6=np.zeros(np.shape(a12))
a6

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
print(a6)
a7=np.ones(np.shape(a6))
a7

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
# Any other number
np.full((2,3), 31)

array([[31, 31, 31],
       [31, 31, 31]])

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a7=np.ones((3,3))
a7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.29214873, 0.81739906],
       [0.35214154, 0.60832388],
       [0.94614646, 0.50580432],
       [0.13919929, 0.21854417]])

In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-1, -3,  0],
       [ 6, -3,  1],
       [ 5, -1,  7]])

In [ ]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
output1 = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)
output1[0:-2,0:-2] = z
print(output1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 1. 1.]
 [0. 9. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a11=np.array([[1,2,3],[4,5,6],[7,8,9]])
a11

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
row,col=a11.shape

In [ ]:
print(row,col)

3 3


In [ ]:
a12=np.zeros((row,col))
for i in range(row):
    for j in range(col):
        a12[i,j]=a7[i,j]+a11[i,j]
a12

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [ ]:
a7+a11

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [ ]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1+a2)
print(a1*a2)
print(a1-a2)
print(a2-a1)
print(a1+(a1*a2))
print(a1/a2)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[3 3 3]
[ 5 12 21]
[0.25 0.4  0.5 ]


Be careful when copying arrays!!!

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)
print(a)

[1 2 3]
[100   2   3]
[1 2 3]


In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a-2

array([-1,  0,  1,  2])

In [ ]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)